# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vchoutas/Programming/camera_basics

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vchoutas/Programming/camera_basics

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vchoutas/Programming/camera_basics/CMakeFiles /home/vchoutas/Programming/camera_basics/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vchoutas/Programming/camera_basics/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named blobs.out

# Build rule for target.
blobs.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blobs.out
.PHONY : blobs.out

# fast build rule for target.
blobs.out/fast:
	$(MAKE) -f CMakeFiles/blobs.out.dir/build.make CMakeFiles/blobs.out.dir/build
.PHONY : blobs.out/fast

#=============================================================================
# Target rules for targets named colorSpaces.out

# Build rule for target.
colorSpaces.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 colorSpaces.out
.PHONY : colorSpaces.out

# fast build rule for target.
colorSpaces.out/fast:
	$(MAKE) -f CMakeFiles/colorSpaces.out.dir/build.make CMakeFiles/colorSpaces.out.dir/build
.PHONY : colorSpaces.out/fast

#=============================================================================
# Target rules for targets named edges.out

# Build rule for target.
edges.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 edges.out
.PHONY : edges.out

# fast build rule for target.
edges.out/fast:
	$(MAKE) -f CMakeFiles/edges.out.dir/build.make CMakeFiles/edges.out.dir/build
.PHONY : edges.out/fast

#=============================================================================
# Target rules for targets named equalization.out

# Build rule for target.
equalization.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 equalization.out
.PHONY : equalization.out

# fast build rule for target.
equalization.out/fast:
	$(MAKE) -f CMakeFiles/equalization.out.dir/build.make CMakeFiles/equalization.out.dir/build
.PHONY : equalization.out/fast

#=============================================================================
# Target rules for targets named harris_corners.out

# Build rule for target.
harris_corners.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 harris_corners.out
.PHONY : harris_corners.out

# fast build rule for target.
harris_corners.out/fast:
	$(MAKE) -f CMakeFiles/harris_corners.out.dir/build.make CMakeFiles/harris_corners.out.dir/build
.PHONY : harris_corners.out/fast

#=============================================================================
# Target rules for targets named histogramms.out

# Build rule for target.
histogramms.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 histogramms.out
.PHONY : histogramms.out

# fast build rule for target.
histogramms.out/fast:
	$(MAKE) -f CMakeFiles/histogramms.out.dir/build.make CMakeFiles/histogramms.out.dir/build
.PHONY : histogramms.out/fast

#=============================================================================
# Target rules for targets named histogramms2D.out

# Build rule for target.
histogramms2D.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 histogramms2D.out
.PHONY : histogramms2D.out

# fast build rule for target.
histogramms2D.out/fast:
	$(MAKE) -f CMakeFiles/histogramms2D.out.dir/build.make CMakeFiles/histogramms2D.out.dir/build
.PHONY : histogramms2D.out/fast

#=============================================================================
# Target rules for targets named shitomasi.out

# Build rule for target.
shitomasi.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shitomasi.out
.PHONY : shitomasi.out

# fast build rule for target.
shitomasi.out/fast:
	$(MAKE) -f CMakeFiles/shitomasi.out.dir/build.make CMakeFiles/shitomasi.out.dir/build
.PHONY : shitomasi.out/fast

camera.o: camera.cpp.o
.PHONY : camera.o

# target to build an object file
camera.cpp.o:
	$(MAKE) -f CMakeFiles/colorSpaces.out.dir/build.make CMakeFiles/colorSpaces.out.dir/camera.cpp.o
.PHONY : camera.cpp.o

camera.i: camera.cpp.i
.PHONY : camera.i

# target to preprocess a source file
camera.cpp.i:
	$(MAKE) -f CMakeFiles/colorSpaces.out.dir/build.make CMakeFiles/colorSpaces.out.dir/camera.cpp.i
.PHONY : camera.cpp.i

camera.s: camera.cpp.s
.PHONY : camera.s

# target to generate assembly for a file
camera.cpp.s:
	$(MAKE) -f CMakeFiles/colorSpaces.out.dir/build.make CMakeFiles/colorSpaces.out.dir/camera.cpp.s
.PHONY : camera.cpp.s

edges.o: edges.cpp.o
.PHONY : edges.o

# target to build an object file
edges.cpp.o:
	$(MAKE) -f CMakeFiles/edges.out.dir/build.make CMakeFiles/edges.out.dir/edges.cpp.o
.PHONY : edges.cpp.o

edges.i: edges.cpp.i
.PHONY : edges.i

# target to preprocess a source file
edges.cpp.i:
	$(MAKE) -f CMakeFiles/edges.out.dir/build.make CMakeFiles/edges.out.dir/edges.cpp.i
.PHONY : edges.cpp.i

edges.s: edges.cpp.s
.PHONY : edges.s

# target to generate assembly for a file
edges.cpp.s:
	$(MAKE) -f CMakeFiles/edges.out.dir/build.make CMakeFiles/edges.out.dir/edges.cpp.s
.PHONY : edges.cpp.s

features/blobs.o: features/blobs.cpp.o
.PHONY : features/blobs.o

# target to build an object file
features/blobs.cpp.o:
	$(MAKE) -f CMakeFiles/blobs.out.dir/build.make CMakeFiles/blobs.out.dir/features/blobs.cpp.o
.PHONY : features/blobs.cpp.o

features/blobs.i: features/blobs.cpp.i
.PHONY : features/blobs.i

# target to preprocess a source file
features/blobs.cpp.i:
	$(MAKE) -f CMakeFiles/blobs.out.dir/build.make CMakeFiles/blobs.out.dir/features/blobs.cpp.i
.PHONY : features/blobs.cpp.i

features/blobs.s: features/blobs.cpp.s
.PHONY : features/blobs.s

# target to generate assembly for a file
features/blobs.cpp.s:
	$(MAKE) -f CMakeFiles/blobs.out.dir/build.make CMakeFiles/blobs.out.dir/features/blobs.cpp.s
.PHONY : features/blobs.cpp.s

features/harris_corners.o: features/harris_corners.cpp.o
.PHONY : features/harris_corners.o

# target to build an object file
features/harris_corners.cpp.o:
	$(MAKE) -f CMakeFiles/harris_corners.out.dir/build.make CMakeFiles/harris_corners.out.dir/features/harris_corners.cpp.o
.PHONY : features/harris_corners.cpp.o

features/harris_corners.i: features/harris_corners.cpp.i
.PHONY : features/harris_corners.i

# target to preprocess a source file
features/harris_corners.cpp.i:
	$(MAKE) -f CMakeFiles/harris_corners.out.dir/build.make CMakeFiles/harris_corners.out.dir/features/harris_corners.cpp.i
.PHONY : features/harris_corners.cpp.i

features/harris_corners.s: features/harris_corners.cpp.s
.PHONY : features/harris_corners.s

# target to generate assembly for a file
features/harris_corners.cpp.s:
	$(MAKE) -f CMakeFiles/harris_corners.out.dir/build.make CMakeFiles/harris_corners.out.dir/features/harris_corners.cpp.s
.PHONY : features/harris_corners.cpp.s

features/shi-tomashi_corners.o: features/shi-tomashi_corners.cpp.o
.PHONY : features/shi-tomashi_corners.o

# target to build an object file
features/shi-tomashi_corners.cpp.o:
	$(MAKE) -f CMakeFiles/shitomasi.out.dir/build.make CMakeFiles/shitomasi.out.dir/features/shi-tomashi_corners.cpp.o
.PHONY : features/shi-tomashi_corners.cpp.o

features/shi-tomashi_corners.i: features/shi-tomashi_corners.cpp.i
.PHONY : features/shi-tomashi_corners.i

# target to preprocess a source file
features/shi-tomashi_corners.cpp.i:
	$(MAKE) -f CMakeFiles/shitomasi.out.dir/build.make CMakeFiles/shitomasi.out.dir/features/shi-tomashi_corners.cpp.i
.PHONY : features/shi-tomashi_corners.cpp.i

features/shi-tomashi_corners.s: features/shi-tomashi_corners.cpp.s
.PHONY : features/shi-tomashi_corners.s

# target to generate assembly for a file
features/shi-tomashi_corners.cpp.s:
	$(MAKE) -f CMakeFiles/shitomasi.out.dir/build.make CMakeFiles/shitomasi.out.dir/features/shi-tomashi_corners.cpp.s
.PHONY : features/shi-tomashi_corners.cpp.s

histograms/equalization.o: histograms/equalization.cpp.o
.PHONY : histograms/equalization.o

# target to build an object file
histograms/equalization.cpp.o:
	$(MAKE) -f CMakeFiles/equalization.out.dir/build.make CMakeFiles/equalization.out.dir/histograms/equalization.cpp.o
.PHONY : histograms/equalization.cpp.o

histograms/equalization.i: histograms/equalization.cpp.i
.PHONY : histograms/equalization.i

# target to preprocess a source file
histograms/equalization.cpp.i:
	$(MAKE) -f CMakeFiles/equalization.out.dir/build.make CMakeFiles/equalization.out.dir/histograms/equalization.cpp.i
.PHONY : histograms/equalization.cpp.i

histograms/equalization.s: histograms/equalization.cpp.s
.PHONY : histograms/equalization.s

# target to generate assembly for a file
histograms/equalization.cpp.s:
	$(MAKE) -f CMakeFiles/equalization.out.dir/build.make CMakeFiles/equalization.out.dir/histograms/equalization.cpp.s
.PHONY : histograms/equalization.cpp.s

histograms/histogramms.o: histograms/histogramms.cpp.o
.PHONY : histograms/histogramms.o

# target to build an object file
histograms/histogramms.cpp.o:
	$(MAKE) -f CMakeFiles/histogramms.out.dir/build.make CMakeFiles/histogramms.out.dir/histograms/histogramms.cpp.o
.PHONY : histograms/histogramms.cpp.o

histograms/histogramms.i: histograms/histogramms.cpp.i
.PHONY : histograms/histogramms.i

# target to preprocess a source file
histograms/histogramms.cpp.i:
	$(MAKE) -f CMakeFiles/histogramms.out.dir/build.make CMakeFiles/histogramms.out.dir/histograms/histogramms.cpp.i
.PHONY : histograms/histogramms.cpp.i

histograms/histogramms.s: histograms/histogramms.cpp.s
.PHONY : histograms/histogramms.s

# target to generate assembly for a file
histograms/histogramms.cpp.s:
	$(MAKE) -f CMakeFiles/histogramms.out.dir/build.make CMakeFiles/histogramms.out.dir/histograms/histogramms.cpp.s
.PHONY : histograms/histogramms.cpp.s

histograms/histogramms2D.o: histograms/histogramms2D.cpp.o
.PHONY : histograms/histogramms2D.o

# target to build an object file
histograms/histogramms2D.cpp.o:
	$(MAKE) -f CMakeFiles/histogramms2D.out.dir/build.make CMakeFiles/histogramms2D.out.dir/histograms/histogramms2D.cpp.o
.PHONY : histograms/histogramms2D.cpp.o

histograms/histogramms2D.i: histograms/histogramms2D.cpp.i
.PHONY : histograms/histogramms2D.i

# target to preprocess a source file
histograms/histogramms2D.cpp.i:
	$(MAKE) -f CMakeFiles/histogramms2D.out.dir/build.make CMakeFiles/histogramms2D.out.dir/histograms/histogramms2D.cpp.i
.PHONY : histograms/histogramms2D.cpp.i

histograms/histogramms2D.s: histograms/histogramms2D.cpp.s
.PHONY : histograms/histogramms2D.s

# target to generate assembly for a file
histograms/histogramms2D.cpp.s:
	$(MAKE) -f CMakeFiles/histogramms2D.out.dir/build.make CMakeFiles/histogramms2D.out.dir/histograms/histogramms2D.cpp.s
.PHONY : histograms/histogramms2D.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... blobs.out"
	@echo "... colorSpaces.out"
	@echo "... edges.out"
	@echo "... edit_cache"
	@echo "... equalization.out"
	@echo "... harris_corners.out"
	@echo "... histogramms.out"
	@echo "... histogramms2D.out"
	@echo "... rebuild_cache"
	@echo "... shitomasi.out"
	@echo "... camera.o"
	@echo "... camera.i"
	@echo "... camera.s"
	@echo "... edges.o"
	@echo "... edges.i"
	@echo "... edges.s"
	@echo "... features/blobs.o"
	@echo "... features/blobs.i"
	@echo "... features/blobs.s"
	@echo "... features/harris_corners.o"
	@echo "... features/harris_corners.i"
	@echo "... features/harris_corners.s"
	@echo "... features/shi-tomashi_corners.o"
	@echo "... features/shi-tomashi_corners.i"
	@echo "... features/shi-tomashi_corners.s"
	@echo "... histograms/equalization.o"
	@echo "... histograms/equalization.i"
	@echo "... histograms/equalization.s"
	@echo "... histograms/histogramms.o"
	@echo "... histograms/histogramms.i"
	@echo "... histograms/histogramms.s"
	@echo "... histograms/histogramms2D.o"
	@echo "... histograms/histogramms2D.i"
	@echo "... histograms/histogramms2D.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

